package go.takethespread;

public enum Settings {
    HOST,
    PORT,
    INSTRUMENT_N,
    INSTRUMENT_F,
    ACCOUNT,
    COMMISSION,
    DEFAULT_SPREAD,
    DEFAULT_SPREAD_USING,
    ENTER_DEVIATION,
    MAX_SIZE,
    TIME_IN_POS_SEC,
    LIMIT_USING,
    MAX_LOSS_N,
    MIN_SPR_CALC_PERIOD_N,
    SPR_CALC_TIME_SEC
}
