package go.takethespread;

public enum Settings {
    ACCOUNT,
    HOST,
    PORT,
    INSTRUMENT_N,
    INSTRUMENT_F,
    ENTER_DEVIATION,
    MAX_SIZE,
    MAX_LOSS_N,
    TIME_IN_POS_SEC,
    SPR_CALC_TIME_SEC,
    MIN_SPR_CALC_PERIOD_N,
    DEFAULT_SPREAD,
    DEFAULT_SPREAD_USING,
    LIMIT_USING,
    COMMISSION
}
