package go.takethespread;

public enum Settings {
    ACCOUNT,
    HOST,
    PORT,
    INSTRUMENT_N,
    INSTRUMENT_F,
    ENTER_DEVIATION,
    MAX_SIZE,
    MAX_LOSS_N,
    TIME_IN_POS_SEC,
    SPREAD_TICKS_AGO_N,
    DEFAULT_SPREAD,
    DEFAULT_SPREAD_USING,
    COMMISSION,
    LIMIT_ENTERING_MODE
}
